[addon]
slug = "libgroupcombatstats"
name = "LibGroupCombatStats"
description = "A library for ESO addons to provide group combat statistics such as DPS, HPS, and ultimate status updates."
authors = ["m00nyONE"]
license = "Artistic-2.0"
category = "library"
tags = ["library", "combat", "dps", "hps", "group"]

[source]
type = "github"
repo = "m00nyONE/LibGroupCombatStats"
branch = "main"
release_type = "release"

[compatibility]
api_version = "101047"
game_versions = ["U44", "U45"]
required_dependencies = []
optional_dependencies = []

[meta]
submitted_by = "brainsnorkel"
submitted_date = 2024-12-28
status = "approved"
reviewers = []
