[addon]
slug = "elmsmarkers"
name = "ElmsMarkers"
description = "Create, manage, and share markers on your 3D world map"
authors = ["bitrock"]
license = "UNLICENSED"
category = "maps"
tags = ["map", "markers"]

[source]
type = "github"
repo = "Fostecks/ElmsMarkers"
branch = "master"
release_type = "branch"

[compatibility]
api_version = "101040"
game_versions = ["U40"]
required_dependencies = ["libaddonmenu-2-0", "odysupporticons"]
optional_dependencies = []

[meta]
submitted_by = "christophergentle"
submitted_date = 2024-12-30
last_reviewed = 2024-12-30
status = "approved"
reviewers = ["christophergentle"]
