[addon]
slug = "libhyper"
name = "LibHyper"
description = "Various functions, textures and fonts used in Hyperioxes' addons."
authors = ["Hyperioxes"]
license = "Unknown"
category = "library"
tags = ["library", "utility"]

[source]
type = "github"
repo = "Hyperioxes/LibHyper"
branch = "main"
release_type = "branch"

[compatibility]
api_version = "101048"
game_versions = ["U46"]
required_dependencies = []
optional_dependencies = []

[meta]
submitted_by = "brainsnorkel"
submitted_date = 2025-12-31
last_reviewed = 2025-12-31
status = "approved"
reviewers = ["brainsnorkel"]
