[addon]
slug = "libchatmessage"
name = "LibChatMessage"
description = "Library for handling chat messages with customizable formatters and generators."
authors = ["sirinsidiator"]
license = "Artistic-2.0"
category = "library"
tags = ["library", "chat", "messaging"]

[source]
type = "github"
repo = "sirinsidiator/ESO-LibChatMessage"
branch = "master"
path = "src"
install_folder = "LibChatMessage"
release_type = "branch"

[compatibility]
api_version = "101048"
game_versions = ["U45"]
required_dependencies = []
optional_dependencies = ["libdebuglogger"]

[meta]
submitted_by = "brainsnorkel"
submitted_date = 2024-12-30
last_reviewed = 2024-12-30
status = "approved"
reviewers = ["brainsnorkel"]
