[addon]
slug = "improveddeathrecap"
name = "ImprovedDeathRecap"
description = "An addon that gives you insight into why you died"
authors = ["Solinur"]
license = "Artistic-2.0"
category = "combat"
tags = ["combat", "death", "analysis"]

[source]
type = "github"
repo = "Solinur/ImprovedDeathRecap"
branch = "master"
path = "ImprovedDeathRecap"
release_type = "tag"

[compatibility]
api_version = "100045"
game_versions = ["U35"]
required_dependencies = ["libaddonmenu"]
optional_dependencies = []

[meta]
submitted_by = "brainsnorkel"
submitted_date = 2024-12-30
last_reviewed = 2024-12-30
status = "approved"
reviewers = ["brainsnorkel"]
