[addon]
slug = "libcustomnames"
name = "LibCustomNames"
description = "A lightweight library for The Elder Scrolls Online that allows custom names for players."
authors = ["m00nyONE", "seadotarley"]
license = "Artistic-2.0"
category = "library"
tags = ["library", "names", "players"]

[source]
type = "github"
repo = "m00nyONE/LibCustomNames"
branch = "main"
release_type = "release"

[compatibility]
api_version = "101048"
game_versions = ["U45"]
required_dependencies = ["libaddonmenu"]
optional_dependencies = []

[meta]
submitted_by = "brainsnorkel"
submitted_date = 2024-12-28
status = "approved"
reviewers = []
